version: '3'

services:
  nginx:
    build: ./nginx
    ports:
      - "443:443"
    volumes:
      - ./volumes/nginx:/etc/nginx
    networks:
      - wordpress-net
    restart: always

  wordpress:
    build: ./wordpress
    volumes:
      - ./volumes/wordpress:/var/www/html
    networks:
      - wordpress-net
    depends_on:
      - mariadb
    restart: always

  mariadb:
    build: ./mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpressuser
      MYSQL_PASSWORD: wordpresspassword
    volumes:
      - ./volumes/db:/var/lib/mysql
    networks:
      - wordpress-net
    restart: always

networks:
  wordpress-net:
    driver: bridge

